//部门树状图
export const EMS_DEPT_TREE = "EMS_DEPT_TREE";
export const EMS_DEPT_TREE_SUCCESS = "EMS_DEPT_TREE_SUCCESS";

//部门列表
export const EMS_DEPT_LIST = "EMS_DEPT_LIST";
export const EMS_DEPT_LIST_SUCCESS = "EMS_DEPT_LIST_SUCCESS";

//部门详细
export const EMS_DEPT_GET = "EMS_DEPT_GET";
export const EMS_DEPT_GET_SUCCESS = "EMS_DEPT_GET_SUCCESS";

//部门创建
export const EMS_DEPT_CREATE = "EMS_DEPT_CREATE";
export const EMS_DEPT_CREATE_SUCCESS = "EMS_DEPT_CREATE_SUCCESS";

//获取部门成员
export const EMS_DEPT_USER_LIST = "EMS_DEPT_USER_LIST";
export const EMS_DEPT_USER_LIST_SUCCESS = "EMS_DEPT_USER_LIST_SUCCESS";
